# Generated by Django 5.2.7 on 2025-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovernmentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the document", max_length=500),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the document", null=True
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="URL to the document on the government website",
                        unique=True,
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        help_text="Date when the document was last updated on the government website"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created in our database",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated in our database",
                    ),
                ),
            ],
            options={
                "verbose_name": "Government Document",
                "verbose_name_plural": "Government Documents",
                "ordering": ["-date_updated"],
            },
        ),
    ]
