# Generated by Django 5.2.7 on 2025-10-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentdocument",
            name="prefecture_code",
            field=models.CharField(
                blank=True, help_text="Code of the prefecture", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="governmentdocument",
            name="prefecture_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the prefecture where this document was found",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="governmentdocument",
            name="region_name",
            field=models.CharField(
                blank=True, help_text="Name of the region", max_length=100, null=True
            ),
        ),
    ]
