# Generated by Django 5.2.7 on 2025-10-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0002_governmentdocument_prefecture_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NegativeKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="The negative keyword to exclude from searches",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this negative keyword was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this negative keyword was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negative Keyword",
                "verbose_name_plural": "Negative Keywords",
                "ordering": ["keyword"],
            },
        ),
    ]
