# Generated by Django 5.2.7 on 2025-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0003_negativekeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentdocument",
            name="is_icpe",
            field=models.BooleanField(
                default=False,
                help_text="Whether this document is related to ICPE (Installations Classées pour la Protection de l'Environnement)",
            ),
        ),
    ]
