# Generated by Django 5.2.7 on 2025-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0005_scrapingtask_scrapingtaskresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="governmentdocument",
            name="link",
            field=models.URLField(
                help_text="URL to the document on the government website",
                max_length=2048,
                unique=True,
            ),
        ),
    ]
