# Generated by Django 5.2.7 on 2025-10-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0006_alter_governmentdocument_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentdocument",
            name="full_page_html",
            field=models.TextField(
                blank=True, help_text="Full HTML content of the scraped page", null=True
            ),
        ),
        migrations.AddField(
            model_name="governmentdocument",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Summary of the document content", null=True
            ),
        ),
    ]
