# Generated by Django 5.2.7 on 2025-10-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0007_governmentdocument_full_page_html_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="governmentdocument",
            name="full_page_html",
        ),
        migrations.AddField(
            model_name="governmentdocument",
            name="full_page_text",
            field=models.TextField(
                blank=True, help_text="Full text content of the scraped page", null=True
            ),
        ),
    ]
