# Generated by Django 5.2.7 on 2025-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0008_remove_governmentdocument_full_page_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentdocument",
            name="animal_number",
            field=models.IntegerField(
                blank=True,
                help_text="Number of animals if this document is related to an animal project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="governmentdocument",
            name="animal_type",
            field=models.CharField(
                blank=True,
                help_text="Type of animal if this document is related to an animal project",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="governmentdocument",
            name="is_animal_project",
            field=models.BooleanField(
                default=False,
                help_text="Whether this document is related to an animal project",
            ),
        ),
        migrations.AddField(
            model_name="governmentdocument",
            name="is_intensive_farming",
            field=models.BooleanField(
                default=False,
                help_text="Whether this document is related to intensive farming",
            ),
        ),
    ]
