# Generated by Django 5.2.7 on 2025-10-25 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0009_governmentdocument_animal_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="governmentdocument",
            name="is_icpe",
        ),
    ]
