# Generated by Django 5.2.7 on 2026-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0010_remove_icpe_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingtask",
            name="days_limit",
            field=models.IntegerField(
                default=30, help_text="Number of days to look back when scraping"
            ),
        ),
    ]
