# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0011_add_days_limit_to_scrapingtask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="governmentdocument",
            old_name="is_animal_project",
            new_name="is_animal_farming_project",
        ),
    ]
