# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0012_rename_is_animal_project_to_is_animal_farming_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="governmentdocument",
            name="is_intensive_farming",
        ),
    ]
